ReactDjangoChat/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from allauth.account.views import LoginView,SignupView, LogoutView

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
   	url(r'^', include('chat.urls', namespace='chat'))
]    

chat/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^$',  views.about, name='about'),
    url(r'new/$', views.new_room, name='new_room'),
    url(r'^(?P<label>[\w-]{,50})/$', views.chat_room, name='chat_room'),
]    

core/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from allauth.account.views import LoginView,SignupView, LogoutView
from .views import user_login, user_signup, user_signout

urlpatterns = [
    url(r'^login/$', user_login, name="login"),
    url(r'^signup/$', user_signup, name="signup"),
    url(r'^signout/$', user_signout, name="signout"),
]    

chat/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from model_utils.models import TimeStampedModel
from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

# Create your models here.

@python_2_unicode_compatible
class Room(TimeStampedModel):
    title = models.CharField(_('Chat Title'), max_length=255, blank=True, null=True)
    label = models.SlugField(unique=True)

    def __unicode__(self):
    	return self.label

    def __str__(self):
    	return self.label


@python_2_unicode_compatible
class Message(TimeStampedModel):
    room = models.ForeignKey(Room, blank=True, null=True, related_name='messages')
    handle = models.TextField()
    message = models.TextField(_('Message'))
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

    def __unicode__(self):
        return '[{timestamp}] {handle}: {message}'.format(**self.as_dict())
    
    def __str__(self):
    	return '[{timestamp}] {handle}: {message}'.format(**self.as_dict())


    @property
    def formatted_timestamp(self):
        return self.timestamp.strftime('%b %-d %-I:%M %p')
    
    def as_dict(self):
        return {'handle': self.handle, 'message': self.message, 'timestamp': self.formatted_timestamp}

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

chat/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import transaction
from django.shortcuts import render, reverse, redirect
from django.contrib.auth.decorators import login_required
import haikunator
from .models import *
# Create your views here.

@login_required
def about(request):
	return render(request, "chat/about.html")

@login_required
def new_room(request):
    new_room = None
    while not new_room:
        with transaction.atomic():
            label = haikunator.haikunate()
            if Room.objects.filter(label=label).exists():
                continue
            new_room = Room.objects.create(label=label)
    return redirect(reverse('chat:chat_room', kwargs={'label':label}))

@login_required
def chat_room(request, label):
    room, created = Room.objects.get_or_create(label=label)
    messages = reversed(room.messages.order_by('-timestamp')[:50])
    return render(request, "chat/room.html", {
        'room': room,
        'messages': messages,
    })

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.


def user_login(request):
	if request.method == "POST":
		print(request.POST)
		username = 	request.POST.get('username')
		password = 	request.POST.get('password')
		user = authenticate(username=username, password=password)

		print(user)
		if user:
			login(request, user)
			return redirect(reverse('chat:about'))
		else:
			messages.warning(request, 'Either password or username is invalid!!')
			return redirect(reverse('core:login'))
	else:
		return render(request,'account/login.html',{}) 


def user_signup(request):
	if request.method == "POST":
		print(request.POST)
		username = 	request.POST.get('username')
		password = 	request.POST.get('password')
		confirm_password = request.POST.get('confirm_password')
		user = User.objects.filter(username=username)
		print(user)
		if not user.count():
			if password != confirm_password:
				messages.warning(request, "passwords are different!!!")
				return redirect(reverse('core:signup'))
			else:
				user = User.objects.create(username=username)
				user.set_password(password)
				user.save()
				messages.warning(request, "Signup successfully, please login")
				return redirect(reverse('chat:about'))
		else:
			messages.warning(request, 'Username already taken!!')
			return redirect(reverse('core:signup'))
	else:
		return render(request,'account/signup.html',{}) 
	



def user_signout(request):
	pass

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}React Django Channels{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600,200' rel='stylesheet' type='text/css'>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'normalize.css' %}">
  <link rel="stylesheet" href="{% static 'skeleton.css' %}">
  <link rel="stylesheet" href="{% static 'chat.css' %}">
</head>
<body>
  <div class="section">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>
  {% block afterbody %}{% endblock afterbody %}
</body>
</html>

templates/chat/about.html
{% extends "base.html" %}

{% block content %}
  <h1>Create New Chat room</h1>
  <p>
    <a class="button button-primary" href="{% url 'chat:new_room' %}">Create new chat room</a>
  </p>
  
{% endblock content %}

templates/chat/room.html
{% extends "base.html" %}

{% block content %}
  {% load staticfiles %}
  <h1>{{ room.label }}</h1>
  <form>
    <table id="chat">
      <tbody>
        {% for message in messages %}
          <tr>
            <td>{{ message.formatted_timestamp }}</td>
            <td>{{ message.handle }}</td>
            <td>{{ message.message }}</td>
          </tr> 
        {% endfor %}
      </tbody>
      <tfoot>
      <tr>
        <td>Type Your Message:</td>
        <td colspan=2>
          <input id="message" type="text" placeholder="message">
          <input type="button" id="go" value="Say it" />
        </td>
      </tfoot>
    </table>
  </form>
{% endblock content %}

{% block afterbody %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
  <script>
    $(function() {
        // When we're using HTTPS, use WSS too.
        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
        var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + "/chat"+window.location.pathname);
        chatsock.onopen = function(){
            console.log("Connected!!!!");
        }

        chatsock.onclosed = function(){
            console.log("Connecting!!!!");
        }


        chatsock.onmessage = function(message) {
            var data = JSON.parse(message.data);
            console.log(data);
            var chat = $("#chat");
            var ele = $('<tr></tr>');
            ele.append(
                $("<td></td>").text(data.timestamp)
            )
            ele.append(
                $("<td></td>").text(data.handle)
            )
            ele.append(
                $("<td></td>").text(data.message)
            )
            
            chat.append(ele)
        };

        $("#go").click(function() {
            console.log($('#message').val());
            var message = {
                message: $('#message').val(),
                handle: '{{request.user.username}}'
            }
            chatsock.send(JSON.stringify(message));
            $("#message").val('').focus();
            return false;
        });
    });
  </script>
{% endblock afterbody %}

templates/index.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Ponynote</title>
  </head>
  <body>
    <div id="root">
    </div>
      {% render_bundle 'main' %}
  </body>
</html> 